config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    resources :posts, only: [:show, :index, :edit, :update, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :members, only: [:show, :index, :edit, :update]
    resources :genres
  end

  scope module: :admin do
    get 'admin_genre_search' => 'posts#search'
    get 'admin_search' => 'searches#search'
  end

  devise_for :members,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end

  namespace :public do
    get 'members/:id/unsubscribe' => 'members#unsubscribe', as:'unsubscribe'
    patch '/members/:id/withdraw' => 'members#withdraw', as:'withdraw'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    get 'genre_search' => 'posts#search'

    resources :posts do
      resources :post_comments, except: [:index, :show, :new, :edit, :update]
      resource :favorites, only: [:create, :destroy]
    end
    resources :members, only: [:show, :edit, :update, :index] do
      member do
        get 'favorites' => 'favorites#favorite'
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :member
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :image

  validates :title, presence: true, length:{ maximum: 30 }
  validates :body, presence: true, length:{ maximum: 800 }

  def get_image(width, height)
    unless image.attached?
    file_path = Rails.root.join('app/assets/images/no-image.jpeg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(member)
    favorites.exists?(member_id: member.id)
  end

  def self.looks(keyword)
    Post.where('title like ?',"%#{keyword}%")
  end

  def self.search(genre_id)
    Post.where(genre_id: genre_id)
  end

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :favorite_count, -> {order(favorite: :desc)}

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @member = @post.member
  end

  def index
    @genres = Genre.all

    if params[:latest]
      @posts = Post.latest
    elsif params[:old]
      @posts = Post.old
    elsif params[:favorite_count]
      @posts = Post.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
    else
      @posts = Post.all
    end
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(4)
  end

  def edit
    @post = Post.find(params[:id])
    @genres = Genre.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post)
      flash[:notice] = "投稿の編集が完了しました。"
    else
      render :edit
      flash[:notice] = "更新に失敗しました。"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def search
    @posts = Post.search(params[:genre_id])
    @genre = Genre.find(params[:genre_id])
    @posts = @posts.page(params[:page]).per(4)
  end

  private

  def post_params
    params.require(:post).permit(:image, :genre_id, :title, :body)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_post.html.erb
<% posts.each do |post| %>
<div class='post'>
  <!--ジャンル-->
  <h6 style="text-align:left">#<%= post.genre.name %></h6>
  <!--タイトル-->
  <h4 style='border: 2px double #333'>
    <%= link_to admin_post_path(post) do %>
      <%= post.title %>
    <% end %>
  </h4>
　<!--画像-->
  <h4>
    <%= link_to admin_post_path(post) do %>
      <% if post.image.attached? %>
        <%= image_tag post.get_image(300,300) %>
      <% else %>
        <%= image_tag 'no-image.jpg', size: "300x300" %>
      <% end %>
    <% end %>
  </h4>
  　<!--ユーザーネーム-->
  <h6>
    （投稿者）
    <%= link_to admin_member_path(post.member) do %>
      <%= post.member.nickname %>さん
    <% end %>
　</h6>
</div>
<% end %>

app/views/admin/posts/edit.html.erb
<div class='container'>
  <div class='row justify-content-center'>
    <div class='col-sm-8 sign'>
      <div class='post-top'>
        投稿編集ページ
      </div>
      <%= flash[:notice] %>
    <div class='new'>
      <%= form_with model:@post, url: admin_post_path(@post) do |f| %>
          <table style='width: 100%;'>
            <tr>
              <th>
                画像
              </th>
              <td>
                <%= f.file_field :image, accept: "image/*" %>
              </td>
              <tr>
              <th>
                ジャンル
              </th>
              <td>
                <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --") %>
              </td>
            </tr>
            <tr>
              <th>
                タイトル
              </th>
              <td>
                <%= f.text_field :title, class: 'col-12' %>
              </td>
            </tr>
            <tr>
              <th>
                投稿内容
              </th>
              <td>
                <%= f.text_area :body, class: 'col-12', rows:15 %>
              </td>
            </tr>
          </table>
      <div>
        <%= f.submit '変更を保存する', class: 'btn btn-green' %>
        <%= link_to '削除する', admin_post_path(@post), method: :delete, class: 'btn btn-red', data: {confirm: "この投稿を削除しますか？"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/posts/index.html.erb
  <div class='container'>
    <div class="search">
      <div class='title'>
        <h3>ユーザの投稿一覧</h3>
      </div>
      <div class='row d-flex p-3'>
        <div class="col-md-4 offset-md-1 col-sm-12">
          <span>
            <%= link_to '新着順', admin_posts_path(latest: "true") %>
            |<%= link_to '古い投稿順', admin_posts_path(old: "true") %>
            |<%= link_to '人気順', admin_posts_path(favorite_count: "true") %>
          </span>
        </div>
        <div class='col-md-2 col-sm-12'>ジャンル検索</div>
        <div class='col-md-4 col-sm-12'>
          <%= form_with url: admin_genre_search_path, method: :get do |f| %>
            <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --") %>
            <%= f.submit '検索', class: 'rounded-pill bg-success text-white border border-success' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row justify-content-around">
      <div class="post-back mb-5 col-12">
        <div class="posts">
          <%= render 'post', posts: @posts %>
        </div>
      <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/search.html.erb
<div class="back">
  <div class="new">
    <div class='container post-back'>
      <div class='title'>#<%= @genre.name %>の検索結果</div>
      <div class='row'>
        <div class='col-12'>
          <div class='posts d-flex justify-content-center'>
            <%= render 'admin/posts/post', posts: @posts %>
            <% if @posts.count == 0 %>
              検索結果が見つかりませんでした
            <% end %>
          </div>
        </div>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="back">
  <div class='new'>
    <div class='container post-back'>
      <div class="mypage p-3">
      <%= flash[:notice] %>
      <div class='row d-flex pt-3 px-3 align-items-top'>
          <div class='col-md-4 col-sm-12 pb-3 px-3'>
             <%= link_to post_path(@post) do %>
              <% if @post.image.attached? %>
                <%= image_tag @post.image, size: "200x200" %>
              <% else %>
                <%= image_tag 'no-image.jpg', size: "200x200" %>
              <% end %>
             <% end %>
          </div>
        <div class='col-md-8 col-sm-12'>
          <div class="row mt-3">
            <div class="col-md-3 col-sm-12 text-left"> ＃<%= @post.genre.name %></div>
            <div class="col-md-9 col-sm-12 text-right">
              投稿日:<%= @post.created_at.strftime('%Y/%m/%d') %>
              <%= link_to admin_member_path(@post.member) do %>
                （<%= @post.member.nickname %>さん）
              <% end %>
            </div>
          </div>
          <h4 class='post-form mb-3'>
            <%= @post.title %>
          </h4>
          <div class='post-form'>
            <!--simple_format＝railsヘルパーの文字列加工-->
            <%= simple_format(@post.body) %>
          </div>
        </div>
      </div>
        <div class='text-center'>
          <%= link_to '編集する', edit_admin_post_path(@post), class: 'btn btn-green col-4' %>
        </div>
        <div class="row post_comments">
          <% @post.post_comments.each do |post_comment| %>
          <div class='com'>
            <span>
              <%= post_comment.member.nickname %>：
              <%= post_comment.comment %>
            </span>
            <span class='text-danger'>
              <%= link_to '削除', admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, data: {confirm: "このコメントを削除しますか？"}, remote: true %>
            </span>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>