config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    resources :posts, only: [:show, :index, :edit, :update, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :members, only: [:show, :index, :edit, :update]
    resources :genres
  end

  scope module: :admin do
    get 'admin_genre_search' => 'posts#search'
    get 'admin_search' => 'searches#search'
  end

  devise_for :members,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end

  namespace :public do
    get 'members/:id/unsubscribe' => 'members#unsubscribe', as:'unsubscribe'
    patch '/members/:id/withdraw' => 'members#withdraw', as:'withdraw'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    get 'genre_search' => 'posts#search'

    resources :posts do
      resources :post_comments, except: [:index, :show, :new, :edit, :update]
      resource :favorites, only: [:create, :destroy]
    end
    resources :members, only: [:show, :edit, :update, :index] do
      member do
        get 'favorites' => 'favorites#favorite'
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_header.html.erb
<div class='logo'>
    <div class="logo-mark">
     <%= link_to root_path do %>｜ひよっこランド｜<% end %>
    </div>
  <nav class='d-flex flex-column'>
    <% if member_signed_in? %>
    <ul>
      <li>ようこそ<%= current_member.nickname %>さん</li>
      <li class='btn btn-orange'><%= link_to posts_path do %><i class="fas fa-users"></i>みんなの投稿<% end %></li>
      <li class='btn btn-orange'><%= link_to new_post_path do %><i class="fas fa-pen"></i>投稿フォーム<% end %></li>
      <li class='btn btn-orange'><%= link_to member_path(current_member) do %><i class="fas fa-user"></i>マイページ<% end %></li>
      <li class='btn btn-orange'><%= link_to favorites_member_path(current_member) do %><i class="fas fa-heart"></i>いいねリスト<% end %></li>
      <li class='btn btn-orange'><%= link_to destroy_member_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>
    </ul>
    <div class='text-md-right mr-md-5 text-sm-center'>
      <%= form_with url: search_path, method: :get do |f| %>
        <%= f.text_field :keyword %>
        <%= f.select :range, options_for_select([['ユーザー'],['投稿']]) %>
        <%= f.submit '検索' %>
      <% end %>
    </div>
      <% elsif admin_signed_in? %>
    <ul>
      <li class='btn btn-orange'><%= link_to admin_root_path do %><i class="fas fa-address-book"></i>ユーザ一覧<% end %></li>
      <li class='btn btn-orange'><%= link_to admin_posts_path do %><i class="fas fa-bars"></i>投稿一覧<% end %></li>
      <li class='btn btn-orange'><%= link_to admin_genres_path do %><i class="fas fa-bookmark"></i>ジャンル一覧<% end %></li>
      <li class='btn btn-orange'><%= link_to destroy_admin_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>
      <div class='text-md-right mr-md-5 text-sm-center'>
        <%= form_with url: admin_search_path, method: :get do |f| %>
          <%= f.text_field :keyword %>
          <%= f.select :range, options_for_select([['ユーザー'],['投稿']]) %>
          <%= f.submit '検索' %>
        <% end %>
      </div>
    </ul>
    <% else %>
    <ul>
      <li class='btn btn-orange'><%= link_to about_path do %><i class="fas fa-star"></i>Aboutページ<% end %></li>
      <li class='btn btn-orange'><%= link_to new_member_registration_path do %><i class="fas fa-user-plus"></i>新規会員登録<% end %></li>
      <li class='btn btn-orange'><%= link_to  new_member_session_path do %><i class="fas fa-sign-in-alt"></i>ログイン<% end %></li>
      <li class='btn btn-orange'><%= link_to new_admin_session_path do %><i class="fas fa-id-card-alt"></i>スタッフログイン<% end %></li>
    </ul>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HiyokkoLand</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
    <div class="admin_wrapper">
    <% else %>
    <div class="member_wrapper">
    <% end %>
      <header>
       <%= render 'layouts/header' %>
      </header>
      <%= yield %>
      <footer><center>ひよっこランド</center></footer>
    </div>
  </body>
</html>